version: '3.9'

services:
  api:
    container_name: base_api
    build: .
    depends_on:
      - db
    ports:
      - 3333:3333
    networks:
      - base_api

  db:
    image: mongo
    container_name: db
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    networks:
      - base_api

networks:
  base_api:
    driver: bridge
